### ISSUE TITLE
error al carga el ui

### ISSUE THREAD

**Issue by sebamenabar** [IIC2233-2015-2/syllabus#474]
Hola, tengo el siguiente error al cargar el ui

``` python
Traceback (most recent call last):
  File "/Users/sebamenabar/Desktop/sebamenabar-repo/Tareas/T06/User/user_main.py", line 5, in <module>
    login_ui = uic.loadUiType("login_screen_mw.ui")
  File "/usr/local/lib/python3.5/site-packages/PyQt4/uic/__init__.py", line 211, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 109, in <module>
  File "/Users/sebamenabar/Desktop/sebamenabar-repo/Tareas/T06/User/assets_rc.py", line 725, in <module>
    qInitResources()
  File "/Users/sebamenabar/Desktop/sebamenabar-repo/Tareas/T06/User/assets_rc.py", line 720, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct, qt_resource_name, qt_resource_data)
TypeError: qRegisterResourceData(int, str, str, str): argument 2 has unexpected type 'str'
```

Me pasa al cargar un archivo ui con imagenes agregadas desde designer, antes no tenia problemas, pero ahora no se por que empezo a aparecer. Lei que era necesario compilar los archivos ui con los siguientes comandos

```
$ pyuic4 login_screen_mw.ui -o login_screen_mwUi.py
$ pyrcc4 icons.qrc -o icons_rc.py
```

El segundo me funciono y dejo de aparecerme este error

``` python
ImportError: No module named icons_rc
```

Pero el primero no me funciona y la terminal me dice `$ exec: python3.5: not found` y me continua apareciendo el error grande de arriba.
Ayuda porfavor

**Comment by lopezjurip** [comment]
Lo pudiste arreglar?

**Comment by sebamenabar** [comment]
estoy trabajando cargando los pixmap desde python, no tengo muchas imagenes asi que no hay problema
